version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      - run:
          name: Deploy application
          command: sls deploy